fix: return noopnoop
Started getting ` TypeError: dbFactory is not a function` now because I missed understanding that getLevelDOWN should return a function.

It is a bit weird to me that the module requires calling that function in the first place if no options are passed nor levelDOWN exists.